[functions]
  directory = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "register.JS,index.html,profile.js,OrderDetails.html,history.html,admin.html,adminlogin.html,OrderDetails.html,home.html,forgot-password.js,maintenance.html,payment.html,topup.html,OrderDetails.js,wallet-topup.js"